# Generated by Django 3.0.7 on 2020-07-08 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plmanager_info',
            fields=[
                ('plid', models.AutoField(primary_key=True, serialize=False)),
                ('plpassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Plmanager_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='平台管理员token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('plmanager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pl_rev.Plmanager_info')),
            ],
        ),
    ]
