# Generated by Django 3.0.7 on 2020-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pl_rev', '0002_plmanager_info_plmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plmanager_info',
            name='plmanager',
            field=models.CharField(max_length=32),
        ),
    ]
