# Generated by Django 3.0.7 on 2020-07-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pl_rev', '0003_auto_20200708_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plmanager_token',
            old_name='plmanager',
            new_name='pl',
        ),
    ]
