# Generated by Django 3.0.3 on 2020-06-14 02:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sup_info',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('spassword', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('scert', models.CharField(max_length=50, null=True)),
                ('sprove', models.ImageField(null=True, upload_to='')),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('sintro', models.CharField(max_length=50, null=True)),
                ('marked', models.IntegerField(null=True)),
                ('stag', models.CharField(max_length=50, null=True)),
                ('skeyword', models.CharField(max_length=50, null=True)),
                ('profit', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sup_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='商家token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('sup', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sup_med.Sup_info')),
            ],
        ),
    ]
