# Generated by Django 3.0.7 on 2020-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_info',
            name='sprove',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
