# Generated by Django 3.0.7 on 2020-06-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0002_auto_20200625_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sup_info',
            name='logo',
        ),
    ]
