# Generated by Django 3.0.7 on 2020-06-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0003_remove_sup_info_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sup_info',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
