# Generated by Django 3.0.7 on 2020-07-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0004_sup_info_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sup_info',
            name='sphone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
