# Generated by Django 3.0.7 on 2020-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0005_sup_info_sphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sup_info',
            name='likesum',
            field=models.IntegerField(null=True),
        ),
    ]
