# Generated by Django 3.0.7 on 2020-07-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0006_sup_info_likesum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_info',
            name='likesum',
            field=models.IntegerField(default=0),
        ),
    ]
