# Generated by Django 3.0.7 on 2020-07-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0008_sup_info_sstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_info',
            name='marked',
            field=models.IntegerField(default=0),
        ),
    ]
