# Generated by Django 3.0.7 on 2020-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0009_auto_20200709_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_info',
            name='logo',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
