# Generated by Django 3.0.7 on 2020-07-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0011_auto_20200710_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_info',
            name='logo',
            field=models.CharField(default='static/sup_med/空.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='saddress',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='scert',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='sintro',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='skeyword',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='sname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='spassword',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='sphone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='sprove',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='sstate',
            field=models.CharField(default='待审核', max_length=32),
        ),
        migrations.AlterField(
            model_name='sup_info',
            name='stag',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
