# Generated by Django 3.0.7 on 2020-07-03 13:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sup_med', '0005_sup_info_sphone'),
        ('user_md', '0004_auto_20200701_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_info',
            fields=[
                ('ordno', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
                ('unotes', models.CharField(max_length=256, null=True)),
                ('ordprice', models.FloatField()),
                ('ordstatus', models.CharField(default='未发货', max_length=32)),
                ('expno', models.IntegerField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sup_med.Sup_info')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.User_info')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
