# Generated by Django 3.0.7 on 2020-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_info',
            name='expno',
            field=models.IntegerField(null=True),
        ),
    ]
