# Generated by Django 3.0.7 on 2020-07-03 14:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0012_pro_info_ptime'),
        ('user_md', '0004_auto_20200701_1822'),
        ('order_md', '0002_auto_20200703_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordrec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.Receiveinfo')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.User_info')),
            ],
        ),
        migrations.CreateModel(
            name='Ordproducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psum', models.IntegerField()),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_up.Pro_info')),
            ],
        ),
        migrations.CreateModel(
            name='Ordpay',
            fields=[
                ('payid', models.AutoField(primary_key=True, serialize=False)),
                ('paytime', models.DateTimeField(default=datetime.datetime.now, verbose_name='支付时间')),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
            ],
        ),
    ]
