# Generated by Django 3.0.7 on 2020-07-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0014_auto_20200704_1733'),
        ('user_md', '0004_auto_20200701_1822'),
        ('order_md', '0003_ordpay_ordproducts_ordrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256, null=True)),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_up.Pro_info')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.User_info')),
            ],
        ),
    ]
