# Generated by Django 3.0.7 on 2020-07-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_md', '0004_auto_20200701_1822'),
        ('order_md', '0004_ordcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rx_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rx', models.ImageField(default='', upload_to='./static/')),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.User_info')),
            ],
        ),
    ]
