# Generated by Django 3.0.7 on 2020-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0005_rx_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ImageField(default='', upload_to='./static/')),
            ],
        ),
    ]
