# Generated by Django 3.0.7 on 2020-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0006_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test',
            new_name='image',
        ),
    ]
