# Generated by Django 3.0.7 on 2020-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0007_auto_20200707_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to='image/%Y/%m/%d'),
        ),
    ]
