# Generated by Django 3.0.7 on 2020-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0009_auto_20200707_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to='image/order_md/%Y%m%d'),
        ),
    ]
