# Generated by Django 3.0.7 on 2020-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0010_auto_20200707_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx_order',
            name='Rx',
            field=models.ImageField(upload_to='image/order_md/%Y%m%d'),
        ),
    ]
