# Generated by Django 3.0.7 on 2020-07-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0011_auto_20200707_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx_order',
            name='Rx',
            field=models.ImageField(upload_to='static/order_md/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(upload_to='static/order_md/%Y%m%d'),
        ),
    ]
