# Generated by Django 3.0.7 on 2020-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0012_auto_20200708_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rx_order',
            name='Rx',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.CharField(max_length=256),
        ),
    ]
