# Generated by Django 3.0.7 on 2020-07-10 02:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_md', '0004_auto_20200701_1822'),
        ('pro_up', '0018_auto_20200709_2320'),
        ('sup_med', '0009_auto_20200709_2210'),
        ('order_md', '0013_auto_20200709_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psum', models.IntegerField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='下单时间')),
                ('unotes', models.CharField(max_length=256, null=True)),
                ('ordprice', models.FloatField()),
                ('ordstatus', models.CharField(default='未发货', max_length=32)),
                ('expno', models.IntegerField(null=True)),
                ('ordno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_md.Order_info')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_up.Pro_info')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sup_med.Sup_info')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_md.User_info')),
            ],
        ),
    ]
