# Generated by Django 3.0.7 on 2020-07-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0014_ordinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordinfo',
        ),
    ]
