# Generated by Django 3.0.7 on 2020-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_md', '0015_delete_ordinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordcom',
            name='comment',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='order_info',
            name='unotes',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
