# Generated by Django 3.0.7 on 2020-07-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_md', '0002_cart_likestores_receiveinfo_records_user_info_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='sid',
        ),
    ]
