# Generated by Django 3.0.7 on 2020-07-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_md', '0003_remove_records_sid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'ordering': ['-stime']},
        ),
    ]
