# Generated by Django 3.0.7 on 2020-07-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_md', '0005_user_info_uimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveinfo',
            name='raddress',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='receiveinfo',
            name='rname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='uname',
            field=models.CharField(max_length=256),
        ),
    ]
