# Generated by Django 3.0.7 on 2020-06-27 02:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_up', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_info',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('psize', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('pusage', models.CharField(max_length=50)),
                ('para', models.CharField(max_length=50)),
                ('problems', models.CharField(max_length=50)),
                ('pkeyword', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('stock', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='商品token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('pro', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='pro_up.Pro_info')),
            ],
        ),
    ]
