# Generated by Django 3.0.7 on 2020-06-27 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0004_sup_info_logo'),
        ('pro_up', '0002_pro_info_pro_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_info',
            name='sid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sup_med.Sup_info'),
            preserve_default=False,
        ),
    ]
