# Generated by Django 3.0.7 on 2020-06-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0004_pro_info_ptype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro_info',
            name='sid',
        ),
    ]
