# Generated by Django 3.0.7 on 2020-06-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sup_med', '0004_sup_info_logo'),
        ('pro_up', '0005_remove_pro_info_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_info',
            name='sid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sup_med.Sup_info'),
        ),
    ]
