# Generated by Django 3.0.7 on 2020-07-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0010_auto_20200628_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_info',
            name='p_picture',
            field=models.ImageField(default='', upload_to='pro_up/static/'),
        ),
    ]
