# Generated by Django 3.0.7 on 2020-07-03 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0011_auto_20200701_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_info',
            name='ptime',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
