# Generated by Django 3.0.7 on 2020-07-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0012_pro_info_ptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_info',
            name='p_picture',
            field=models.ImageField(default='', upload_to='./static/'),
        ),
    ]
