# Generated by Django 3.0.7 on 2020-07-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0014_auto_20200704_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_info',
            name='p_picture',
            field=models.ImageField(upload_to='image/pro_md/%Y%m%d'),
        ),
    ]
