# Generated by Django 3.0.7 on 2020-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_up', '0017_auto_20200709_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_info',
            name='p_picture',
            field=models.CharField(max_length=256),
        ),
    ]
