# Generated by Django 3.0.7 on 2020-07-09 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_info',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=50)),
                ('dpassword', models.CharField(max_length=50)),
                ('dprove', models.CharField(max_length=50)),
                ('dtitle', models.CharField(max_length=50, null=True)),
                ('dintro', models.CharField(max_length=50, null=True)),
                ('dphone', models.CharField(max_length=50, null=True)),
                ('dstate', models.CharField(default='待审核', max_length=50)),
                ('skilled', models.CharField(max_length=50, null=True)),
                ('dscore', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='医生token')),
                ('expiration_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('doc', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='doc_ch.Doc_info')),
            ],
        ),
    ]
